# Generated by Django 5.1.4 on 2025-01-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('available', models.BooleanField(default=True)),
                ('marka_car', models.CharField(default='Unknown', max_length=100)),
                ('color_car', models.CharField(default='Unknown', max_length=100)),
                ('country_car', models.CharField(default='Unknown', max_length=100)),
                ('year_car', models.PositiveIntegerField(default='Unknown')),
                ('mileage_car', models.PositiveIntegerField()),
                ('engine_car', models.CharField(default='Unknown', max_length=100)),
                ('transmission_car', models.CharField(default='Unknown', max_length=50)),
                ('hand_drive', models.CharField(default='Unknown', max_length=50)),
                ('type_oil', models.CharField(default='Unknown', max_length=50)),
                ('gear_car', models.CharField(default='Unknown', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
